import Columns from "../constants/columns.js";
import BaseQueries from "../query/BaseQueries.js";
import QueryStrings from "../query/QueryStrings.js";
import { CATEGORY_JOIN, CATEGORY_JOIN_SELECT } from "./categories.js";
import { COLUMN_CATEGORY_ID, PRODUCTS_JOIN, PRODUCTS_JOIN_SELECT, TABLE_NAME_PRODUCTS } from "./products.js";
import { TABLE_NAME_TRANSACTIONS, TRANSACTION_JOIN, TRANSACTION_JOIN_SELECT } from "./transactions.js";

// TABLE NAME AND COLUMNS

const TABLE_NAME = "transactionproducts";

const COLUMN_PRODUCTS_ID = "productId";
const COLUMN_TRANSACTION_ID = "transactionId";
const COLUMN_PRICE = "price";
const COLUMN_AMOUNT = "amount";
const COLUMN_WEIGHT = "weight";

// JOIN

export const TABLE_NAME_TRANSACTION_PRODUCTS = "transactionproducts";

// QUERIES

function QUERY_GET_ALL_BY_TRANSACTION() {
  const COLUMNS = [Columns.ID, COLUMN_PRODUCTS_ID, COLUMN_TRANSACTION_ID, COLUMN_PRICE, COLUMN_AMOUNT, COLUMN_WEIGHT, Columns.USER_ID];

  let QUERY = QueryStrings.SELECT_JOIN_BASE(TABLE_NAME, COLUMNS);

  QUERY += PRODUCTS_JOIN_SELECT();
  QUERY += CATEGORY_JOIN_SELECT();
  QUERY += QueryStrings.FROM(TABLE_NAME);
  QUERY += PRODUCTS_JOIN(TABLE_NAME, COLUMN_PRODUCTS_ID);
  QUERY += CATEGORY_JOIN(TABLE_NAME_PRODUCTS, COLUMN_CATEGORY_ID);

  QUERY += QueryStrings.WHERE(TABLE_NAME, COLUMN_TRANSACTION_ID);

  QUERY += `AND ${TABLE_NAME}.${Columns.IS_ACTIVE} = 1`;

  return QUERY;
}

function QUERY_GET_ALL_BY_PRODUCT() {
  const COLUMNS = [Columns.ID, COLUMN_PRODUCTS_ID, COLUMN_TRANSACTION_ID, COLUMN_PRICE, COLUMN_AMOUNT, COLUMN_WEIGHT, Columns.USER_ID];

  let QUERY = QueryStrings.SELECT_JOIN_BASE(TABLE_NAME, COLUMNS);

  QUERY += TRANSACTION_JOIN_SELECT();
  QUERY += QueryStrings.FROM(TABLE_NAME);
  QUERY += TRANSACTION_JOIN(TABLE_NAME, COLUMN_TRANSACTION_ID);
  QUERY += QueryStrings.WHERE(TABLE_NAME, COLUMN_PRODUCTS_ID);
  QUERY += `AND ${TABLE_NAME_TRANSACTIONS}.${Columns.IS_ACTIVE} = 1`;
  return QUERY;
}

function QUERY_GET() {
  const COLUMNS = [Columns.ID, COLUMN_NAME, COLUMN_ICON];
  return BaseQueries.select(TABLE_NAME, COLUMNS);
}

function QUERY_CREATE() {
  const COLUMNS = [COLUMN_PRODUCTS_ID, COLUMN_TRANSACTION_ID, COLUMN_PRICE, COLUMN_AMOUNT, COLUMN_WEIGHT, Columns.USER_ID];
  return BaseQueries.create(TABLE_NAME, COLUMNS);
}

function QUERY_CREATE_LIST() {
  const COLUMNS = [COLUMN_PRODUCTS_ID, COLUMN_TRANSACTION_ID, COLUMN_PRICE, COLUMN_AMOUNT, COLUMN_WEIGHT, Columns.USER_ID];
  return BaseQueries.insertAll(TABLE_NAME, COLUMNS);
}

function QUERY_UPDATE() {
  const COLUMNS = [COLUMN_PRODUCTS_ID, COLUMN_TRANSACTION_ID, COLUMN_PRICE, COLUMN_AMOUNT, COLUMN_WEIGHT];
  return BaseQueries.update(TABLE_NAME, COLUMNS);
}

function QUERY_DELETE() {
  return BaseQueries.delete(TABLE_NAME);
}

function QUERY_DELETE_BY_TRANSACTION_ID() {
  const QUERY = `UPDATE ${TABLE_NAME} SET ${Columns.IS_ACTIVE} = 0, ${Columns.DELETED_AT} = NOW() WHERE ${COLUMN_TRANSACTION_ID} = ?`;
  return QUERY;
}

export { QUERY_GET, QUERY_GET_ALL_BY_TRANSACTION, QUERY_GET_ALL_BY_PRODUCT, QUERY_CREATE, QUERY_CREATE_LIST, QUERY_UPDATE, QUERY_DELETE, QUERY_DELETE_BY_TRANSACTION_ID };
